import { test, expect } from "@playwright/test";
import { createClient } from "@supabase/supabase-js";
import { createServerClient } from "@supabase/ssr";
import { readFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";

// This test makes two real, short Luna requests and creates a temporary user.
// The user's generations, votes, profile, and Auth record are deleted afterward.
test("guests see only sign-in; members generate, share, and persist a single changeable vote", async ({ browser, baseURL }) => {
  const admin = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false, autoRefreshToken: false } });
  const email = `humor-e2e-${randomUUID()}@example.com`;
  const password = `${randomUUID()}Aa1!`;
  const { data: created, error: createError } = await admin.auth.admin.createUser({ email, password, email_confirm: true });
  expect(createError).toBeNull();
  const userId = created.user!.id;
  const guest = await browser.newContext();
  const member = await browser.newContext();
  try {
    const guestPage = await guest.newPage();
    await guestPage.goto("/");
    await expect(guestPage.getByRole("heading", { name: "Sign in to continue" })).toBeVisible();
    await expect(guestPage.locator("article")).toHaveCount(0);
    await guestPage.goto("/create");
    await expect(guestPage.getByRole("heading", { name: "Sign in to continue" })).toBeVisible();
    await expect(guestPage.getByLabel("Search templates")).toHaveCount(0);
    await expect(guestPage.getByRole("link", { name: "Sign in with Google" })).toHaveAttribute("href", "/auth/login?next=%2Fcreate");
    await guestPage.goto("/captions/not-a-uuid");
    await expect(guestPage.getByRole("heading", { name: "Sign in to continue" })).toBeVisible();

    const authCookies: { name: string; value: string }[] = [];
    const auth = createServerClient(process.env.SUPABASE_URL!, process.env.SUPABASE_ANON_KEY!, {
      cookies: { getAll: () => [], setAll: (items) => { authCookies.push(...items); } },
    });
    const { error: signInError } = await auth.auth.signInWithPassword({ email, password });
    expect(signInError).toBeNull();
    await member.addCookies(authCookies.map(({ name, value }) => ({ name, value, url: baseURL!, sameSite: "Lax" as const })));
    const page = await member.newPage();
    const errors: string[] = [];
    page.on("pageerror", (error) => errors.push(error.message));
    await page.goto("/create");
    await expect(page.getByRole("button", { name: /^Use (?!today)/ })).toHaveCount(8);
    await page.getByLabel("Search templates").fill("awkward");
    await expect(page.getByRole("button", { name: /^Use (?!today)/ })).toHaveCount(1);
    await expect(page.getByRole("button", { name: "Use Monkey Puppet" })).toBeVisible();
    await page.getByLabel("Search templates").fill("no such template");
    await expect(page.getByText("No templates for that search.")).toBeVisible();
    await page.getByRole("button", { name: "Clear filters" }).click();
    await page.getByLabel("Template category").selectOption("Waiting");
    await expect(page.getByRole("button", { name: /^Use (?!today)/ })).toHaveCount(1);
    await page.getByLabel("Template category").selectOption("All templates");
    await page.screenshot({ path: "test-results/template-gallery.png", fullPage: true });
    await expect(page.getByRole("button", { name: "Generate & publish meme" })).toBeDisabled();
    await page.getByRole("button", { name: "Upload a photo", exact: true }).click();
    await page.getByLabel("Pick your territory").selectOption("Dorm life");
    const prompt = "My dorm laundry pile has claimed the second half of my room and now wants to split the rent.";
    await page.getByLabel("Give it some context").fill(prompt);
    await page.getByLabel("Pick your meme photo").setInputFiles({ name: "broken.jpg", mimeType: "image/jpeg", buffer: Buffer.from("not actually an image") });
    await page.getByRole("button", { name: "Generate & publish meme" }).click();
    await expect(page.getByText("That image couldn't be opened.", { exact: false })).toBeVisible();
    await expect(page.getByLabel("Pick your territory")).toHaveValue("Dorm life");
    const { count: rejectedCount } = await admin.from("generation_requests").select("id", { count: "exact", head: true }).eq("user_id", userId);
    expect(rejectedCount).toBe(0);
    await page.getByLabel("Pick your meme photo").setInputFiles("tests/fixtures/cat.jpg");
    await expect(page.getByAltText("Your selected meme photo")).toBeVisible();
    await page.screenshot({ path: "test-results/create-meme.png", fullPage: true });
    await page.getByRole("button", { name: "Generate & publish meme" }).click();
    await expect(page.getByRole("link", { name: "See your meme & share it" })).toBeVisible({ timeout: 45_000 });
    await expect(page.getByRole("heading", { name: "Your recent attempts" })).toBeVisible();
    await expect(page.getByRole("link", { name: "View meme" })).toBeVisible();
    const { data: requests } = await admin.from("generation_requests").select("prompt,system_prompt,model,status,image_path,template_id").eq("user_id", userId);
    expect(requests).toHaveLength(1);
    expect(requests![0]).toMatchObject({ prompt, model: "gpt-6-luna", status: "completed", template_id: null });
    expect(requests![0].system_prompt.length).toBeGreaterThan(50);
    await page.getByRole("link", { name: "See your meme & share it" }).click();
    await page.waitForURL("**/captions/*");
    const captionURL = page.url();
    await expect(page.locator("figure img")).toBeVisible();
    await expect.poll(() => page.locator("figure img").evaluate((image: HTMLImageElement) => image.naturalWidth)).toBeGreaterThan(0);
    expect(requests![0].image_path).toMatch(new RegExp(`^${userId}/.+\\.jpg$`));
    const { data: storedImage, error: imageError } = await admin.storage.from("meme-images").download(requests![0].image_path);
    expect(imageError).toBeNull();
    expect(storedImage?.type).toContain("image/jpeg");
    await expect(page.getByText("0 score · 0 votes")).toBeVisible();
    await page.getByRole("button", { name: "↑ Funny", exact: true }).click();
    await expect(page.getByText("+1 score · 1 vote · Your vote is saved")).toBeVisible();
    await page.reload();
    await expect(page.getByRole("button", { name: "↑ Funny", exact: true })).toHaveAttribute("aria-pressed", "true");
    await page.getByRole("button", { name: "↓ Not quite", exact: true }).click();
    await expect(page.getByText("-1 score · 1 vote · Your vote is saved")).toBeVisible();
    const { data: votes } = await admin.from("caption_votes").select("value").eq("user_id", userId);
    expect(votes).toEqual([{ value: -1 }]);
    await guestPage.goto(captionURL);
    await expect(guestPage.getByRole("heading", { name: "Sign in to continue" })).toBeVisible();
    await expect(guestPage.getByRole("button", { name: "↑ Funny", exact: true })).toHaveCount(0);
    await expect(guestPage.locator("figure img")).toHaveCount(0);
    await expect(guestPage.getByText("-1 score · 1 vote")).toHaveCount(0);
    const imageURL = new URL(`${new URL(captionURL).pathname}/image`, baseURL!).href;
    expect((await guestPage.request.get(imageURL)).status()).toBe(401);
    expect((await page.request.get(imageURL)).status()).toBe(200);
    // Unpublished images stay private even if their path is known.
    const privatePath = `${userId}/unpublished.jpg`;
    const photo = await readFile("tests/fixtures/cat.jpg");
    const { error: privateUploadError } = await admin.storage.from("meme-images").upload(privatePath, photo, { contentType: "image/jpeg" });
    expect(privateUploadError).toBeNull();
    const anon = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_ANON_KEY!, { auth: { persistSession: false } });
    const { error: privateReadError } = await anon.storage.from("meme-images").createSignedUrl(privatePath, 60);
    expect(privateReadError).not.toBeNull();
    const { error: publishedReadError } = await anon.storage.from("meme-images").createSignedUrl(requests![0].image_path, 60);
    expect(publishedReadError).not.toBeNull();
    const { error: guestFeedError } = await anon.rpc("caption_feed");
    expect(guestFeedError).not.toBeNull();
    const { error: ownerReadError } = await auth.storage.from("meme-images").createSignedUrl(privatePath, 60);
    expect(ownerReadError).toBeNull();
    await member.grantPermissions(["clipboard-read", "clipboard-write"]);
    await page.getByRole("button", { name: "Share", exact: true }).click();
    await expect(page.getByText("Link copied!")).toBeVisible();
    expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(captionURL);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto("/");
    await page.locator("figure img").first().scrollIntoViewIfNeeded();
    await expect.poll(() => page.locator("figure img").first().evaluate((image: HTMLImageElement) => image.naturalWidth)).toBeGreaterThan(0);
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: "test-results/mobile-feed.png", fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.setViewportSize({ width: 1280, height: 900 });
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: "test-results/desktop-feed.png", fullPage: true });
    await page.getByRole("link", { name: "Top this week" }).click();
    await expect(page.locator(`a[href="${new URL(captionURL).pathname}"]`)).toBeVisible();
    // A trusted template follows the same vision / storage / publication path.
    await page.goto("/create");
    await page.getByRole("button", { name: "Use Surprised Pikachu" }).click();
    await expect(page.getByAltText("Selected template: Surprised Pikachu")).toBeVisible();
    await page.getByLabel("Give it some context").fill("I checked the forecast before leaving my dorm and NYC still managed to surprise me with rain.");
    // Forged template IDs must be rejected before consuming quota or reading files.
    await page.locator('input[name="template_id"]').evaluate((input: HTMLInputElement) => { input.value = "../../.env.local"; });
    await page.getByRole("button", { name: "Generate & publish meme" }).click();
    await expect(page.getByText("Choose a template from the gallery or upload a photo.")).toBeVisible();
    const { count: afterForgery } = await admin.from("generation_requests").select("id", { count: "exact", head: true }).eq("user_id", userId);
    expect(afterForgery).toBe(1);
    await page.locator('input[name="template_id"]').evaluate((input: HTMLInputElement) => { input.value = "surprised-pikachu"; });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: "test-results/mobile-create.png", fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.getByRole("button", { name: "Generate & publish meme" }).click();
    await expect(page.getByRole("link", { name: "See your meme & share it" })).toBeVisible({ timeout: 45_000 });
    const { data: templateRequest } = await admin.from("generation_requests").select("status,image_path,template_id").eq("user_id", userId).eq("template_id", "surprised-pikachu").single();
    expect(templateRequest).toMatchObject({ status: "completed", template_id: "surprised-pikachu" });
    await page.getByRole("link", { name: "See your meme & share it" }).click();
    await page.waitForURL("**/captions/*");
    await expect.poll(() => page.locator("figure img").evaluate((image: HTMLImageElement) => image.naturalWidth)).toBeGreaterThan(0);
    await page.getByRole("button", { name: "Sign out", exact: true }).click();
    await expect(page.getByRole("link", { name: "Sign in with Google" })).toBeVisible();
    await page.goBack();
    await expect(page.getByRole("heading", { name: "Sign in to continue" })).toBeVisible();
    await expect(page.locator("figure img")).toHaveCount(0);
    expect(errors).toEqual([]);
  } finally {
    await guest.close();
    await member.close();
    const { data: images } = await admin.storage.from("meme-images").list(userId);
    if (images?.length) {
      const { error: cleanupError } = await admin.storage.from("meme-images").remove(images.map((image) => `${userId}/${image.name}`));
      expect(cleanupError).toBeNull();
    }
    const { error } = await admin.auth.admin.deleteUser(userId);
    expect(error).toBeNull();
  }
});
