create table if not exists public.jokes (
  id bigint generated by default as identity primary key,
  setup text not null unique,
  punchline text not null,
  created_at timestamptz not null default now()
);

alter table public.jokes enable row level security;

drop policy if exists "Anyone can read jokes" on public.jokes;
create policy "Anyone can read jokes"
  on public.jokes
  for select
  to anon
  using (true);

grant usage on schema public to anon;
grant select on table public.jokes to anon;

insert into public.jokes (setup, punchline)
values
  ('Why did the developer go broke?', 'Because they used up all their cache.'),
  ('Why do programmers prefer dark mode?', 'Because light attracts bugs.'),
  ('What is a programmer''s favorite place to hang out?', 'The Foo Bar.'),
  ('Why was the JavaScript developer sad?', 'Because they did not Node how to Express themselves.')
on conflict (setup) do update
set punchline = excluded.punchline;
